parameters:
  gadget.http.cookie_file: "%kernel.project_dir%/var/cookies.json"

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Gadget\Http\:
    resource: "../../../src/"
    exclude:
      - "../../../src/DependencyInjection/"
      - "../../../src/Entity/"
      - "../../../src/Kernel.php"

  Gadget\Http\Client\CookieMiddleware:
    arguments:
      $cookieFile: "%gadget.http.cookie_file%"
