services:

  gadget.http.client:
    autowire: true
    class: Gadget\Http\Client\Client

  gadget.http.cookie_jar:
    autowire: true
    class: Gadget\Http\Cookie\CookieJar

  gadget.http.middleware_container:
    autowire: true
    class: Gadget\Http\Client\MiddlewareContainer

  gadget.http.request_builder:
    autowire: true
    class: Gadget\Http\Message\RequestBuilder
