services:
  _defaults:
    autowire: true
    autoconfigure: true

  Gadget\Http\:
    resource: '../../../src/'
    exclude:
      - '../../../src/DependencyInjection/'
      - '../../../src/Entity/'
      - '../../../src/Kernel.php'
